# Generated by Django 2.0.2 on 2018-03-05 00:22

from django.db import migrations, models
import django.db.models.deletion
import reader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Changing this could potentially break image paths and other URLs', unique=True)),
                ('alt', models.CharField(blank=True, help_text='The original title, or title in another language', max_length=200, verbose_name='Alternate title')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Author')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='Artist')),
                ('description', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
                ('format', models.PositiveSmallIntegerField(choices=[(0, 'Manga'), (1, 'Toon'), (2, 'Classic'), (3, 'LTR Book'), (4, 'RTL Book')], default=0, max_length=1)),
                ('cover', models.ImageField(upload_to=reader.models.Comic.path)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stub', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='tags',
            field=models.ManyToManyField(to='reader.Tag'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Comic'),
        ),
    ]
