# Generated by Django 2.0.2 on 2018-03-09 00:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('reader', '0002_auto_20180304_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('hslices', models.PositiveSmallIntegerField()),
                ('vslices', models.PositiveSmallIntegerField()),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='language',
            field=models.CharField(default='en_US', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chapter',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default='test', help_text='Changing this could potentially break image paths and other URLs', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='subchapter',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='chapter',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='chapter_title',
            field=models.CharField(blank=True, help_text='Replace the default chapter title with a custom format. Example: "{num}{ord} Stage" returns "2nd Stage"', max_length=200, verbose_name='Custom chapter title'),
        ),
        migrations.AddField(
            model_name='comic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='joint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reader.Joint'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='protection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.Protection'),
        ),
    ]
