# Generated by Django 2.0.2 on 2018-03-09 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20180308_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='protection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.Protection'),
        ),
    ]
