# Generated by Django 2.0.2 on 2018-03-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_auto_20180308_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='joint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reader.Joint'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='protection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.Protection'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subchapter',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reader.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
