# Generated by Django 2.0.2 on 2018-03-09 04:32

from django.db import migrations, models
import django.db.models.deletion
import reader.models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_auto_20180308_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to=reader.models.Page.path)),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('mime', models.CharField(max_length=16)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='reader.Chapter')),
            ],
        ),
    ]
