# Generated by Django 2.0.2 on 2018-03-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_auto_20180311_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
