# Generated by Django 2.0.2 on 2018-03-12 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_auto_20180311_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(editable=False, help_text='Changing this could potentially break image paths and other URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.SlugField(editable=False, help_text='Changing this could potentially break image paths and other URLs', unique=True),
        ),
    ]
