# Generated by Django 2.0.2 on 2018-03-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0014_auto_20180312_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='protection',
            field=models.OneToOneField(blank=True, default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='reader.Protection'),
            preserve_default=False,
        ),
    ]
