# Generated by Django 2.0.2 on 2018-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0015_auto_20180312_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='slug',
        ),
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.SlugField(help_text='Changing this will break URLs', unique=True),
        ),
    ]
