# Generated by Django 2.0.2 on 2018-03-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0016_auto_20180312_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='comic',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='author',
        ),
        migrations.AddField(
            model_name='comic',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='comic_comic_artist', to='reader.Person'),
        ),
        migrations.AddField(
            model_name='comic',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='comic_comic_author', to='reader.Person'),
        ),
    ]
