# Generated by Django 2.0.2 on 2018-03-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0017_auto_20180312_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
