# Generated by Django 2.0.2 on 2018-03-12 21:45

from django.db import migrations, models
import languages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0020_auto_20180312_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='language',
        ),
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Synopsis'),
        ),
    ]
