# Generated by Django 2.0.2 on 2018-03-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0021_auto_20180312_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='protection',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.Protection'),
        ),
    ]
