# Generated by Django 2.0.2 on 2018-03-12 23:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('reader', '0022_auto_20180312_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Filesystem identifier for this object', unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Filesystem identifier for this object', unique=True, verbose_name='Unique ID'),
        ),
    ]
