# Generated by Django 2.0.2 on 2018-03-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0023_auto_20180312_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('file',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
