# Generated by Django 2.0.2 on 2018-03-26 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0024_auto_20180325_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
