# Generated by Django 2.0.2 on 2018-03-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0025_chapter_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='teamslug', help_text='Changing this may break URLs', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
