# Generated by Django 2.0.2 on 2018-03-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0026_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subchapter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
