# Generated by Django 2.0.2 on 2018-03-27 00:55

from django.db import migrations, models
import reader.models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0028_remove_chapter_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protection',
            name='expires',
            field=models.DateTimeField(default=reader.models.Protection.default_expiry),
        ),
    ]
