# Generated by Django 2.0.2 on 2018-03-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0028_remove_chapter_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
