# Generated by Django 2.0.4 on 2018-04-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0033_auto_20180407_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licensee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('homepage', models.CharField(blank=True, help_text="Link to liscensee's website", max_length=80)),
                ('logo', models.ImageField(blank=True, help_text="Licensee's logo, preferably transparent", upload_to='misc')),
            ],
        ),
    ]
