# Generated by Django 2.0.4 on 2018-04-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0035_comic_licenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
