# Generated by Django 2.0.4 on 2018-05-09 02:16

from django.db import migrations, models
import reader.models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0038_auto_20180415_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='language',
        ),
        migrations.AddField(
            model_name='comic',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.ImageField(height_field='height', max_length=200, storage=reader.models.PageStorage(), upload_to=reader.models.Page.path, width_field='width'),
        ),
    ]
