# Generated by Django 2.0.4 on 2018-05-20 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0041_auto_20180519_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
