# Generated by Django 2.0.4 on 2018-05-20 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0042_chapter_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('-published_at',)},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='protected',
            field=models.BooleanField(default=False, help_text='Not yet implemented!'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Setting a future time will cause the chapter to remain unpublished until then'),
        ),
    ]
