# Generated by Django 2.1.1 on 2018-09-15 05:25

from django.db import migrations, models
import reader.models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0043_auto_20180520_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='adult',
            field=models.BooleanField(db_index=True, default=False, help_text='Show NSFW warning when attempting to view the comic or its chapters'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='expires',
            field=models.DateTimeField(default=reader.models.default_expiry),
        ),
        migrations.DeleteModel(
            name='SitePreferenceModel',
        ),
    ]
