# Generated by Django 2.1.8 on 2019-04-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0044_auto_20180914_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='team',
            field=models.ManyToManyField(blank=True, default=1, to='reader.Team'),
        ),
    ]
