# Generated by Django 2.0.4 on 2018-05-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180519_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='enable_comments',
            field=models.BooleanField(default=False, verbose_name='enable comments'),
        ),
    ]
