# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

LANGUAGES = (
    ("af", _(u"Afrikaans")),
    ("af-ZA", _(u"Afrikaans (South Africa)")),
    ("ar", _(u"Arabic")),
    ("ar-AE", _(u"Arabic (U.A.E.)")),
    ("ar-BH", _(u"Arabic (Bahrain)")),
    ("ar-DZ", _(u"Arabic (Algeria)")),
    ("ar-EG", _(u"Arabic (Egypt)")),
    ("ar-IQ", _(u"Arabic (Iraq)")),
    ("ar-JO", _(u"Arabic (Jordan)")),
    ("ar-KW", _(u"Arabic (Kuwait)")),
    ("ar-LB", _(u"Arabic (Lebanon)")),
    ("ar-LY", _(u"Arabic (Libya)")),
    ("ar-MA", _(u"Arabic (Morocco)")),
    ("ar-OM", _(u"Arabic (Oman)")),
    ("ar-QA", _(u"Arabic (Qatar)")),
    ("ar-SA", _(u"Arabic (Saudi Arabia)")),
    ("ar-SY", _(u"Arabic (Syria)")),
    ("ar-TN", _(u"Arabic (Tunisia)")),
    ("ar-YE", _(u"Arabic (Yemen)")),
    ("az", _(u"Azeri (Latin)")),
    ("az-AZ", _(u"Azeri (Latin) (Azerbaijan)")),
    ("az-AZ", _(u"Azeri (Cyrillic) (Azerbaijan)")),
    ("be", _(u"Belarusian")),
    ("be-BY", _(u"Belarusian (Belarus)")),
    ("bg", _(u"Bulgarian")),
    ("bg-BG", _(u"Bulgarian (Bulgaria)")),
    ("bs-BA", _(u"Bosnian (Bosnia and Herzegovina)")),
    ("ca", _(u"Catalan")),
    ("ca-ES", _(u"Catalan (Spain)")),
    ("cs", _(u"Czech")),
    ("cs-CZ", _(u"Czech (Czech Republic)")),
    ("cy", _(u"Welsh")),
    ("cy-GB", _(u"Welsh (United Kingdom)")),
    ("da", _(u"Danish")),
    ("da-DK", _(u"Danish (Denmark)")),
    ("de", _(u"German")),
    ("de-AT", _(u"German (Austria)")),
    ("de-CH", _(u"German (Switzerland)")),
    ("de-DE", _(u"German (Germany)")),
    ("de-LI", _(u"German (Liechtenstein)")),
    ("de-LU", _(u"German (Luxembourg)")),
    ("dv", _(u"Divehi")),
    ("dv-MV", _(u"Divehi (Maldives)")),
    ("el", _(u"Greek")),
    ("el-GR", _(u"Greek (Greece)")),
    ("en", _(u"English")),
    ("en-AU", _(u"English (Australia)")),
    ("en-BZ", _(u"English (Belize)")),
    ("en-CA", _(u"English (Canada)")),
    ("en-CB", _(u"English (Caribbean)")),
    ("en-GB", _(u"English (United Kingdom)")),
    ("en-IE", _(u"English (Ireland)")),
    ("en-JM", _(u"English (Jamaica)")),
    ("en-NZ", _(u"English (New Zealand)")),
    ("en-PH", _(u"English (Republic of the Philippines)")),
    ("en-TT", _(u"English (Trinidad and Tobago)")),
    ("en-US", _(u"English (United States)")),
    ("en-ZA", _(u"English (South Africa)")),
    ("en-ZW", _(u"English (Zimbabwe)")),
    ("eo", _(u"Esperanto")),
    ("es", _(u"Spanish")),
    ("es-AR", _(u"Spanish (Argentina)")),
    ("es-BO", _(u"Spanish (Bolivia)")),
    ("es-CL", _(u"Spanish (Chile)")),
    ("es-CO", _(u"Spanish (Colombia)")),
    ("es-CR", _(u"Spanish (Costa Rica)")),
    ("es-DO", _(u"Spanish (Dominican Republic)")),
    ("es-EC", _(u"Spanish (Ecuador)")),
    ("es-ES", _(u"Spanish (Castilian)")),
    ("es-ES", _(u"Spanish (Spain)")),
    ("es-GT", _(u"Spanish (Guatemala)")),
    ("es-HN", _(u"Spanish (Honduras)")),
    ("es-MX", _(u"Spanish (Mexico)")),
    ("es-NI", _(u"Spanish (Nicaragua)")),
    ("es-PA", _(u"Spanish (Panama)")),
    ("es-PE", _(u"Spanish (Peru)")),
    ("es-PR", _(u"Spanish (Puerto Rico)")),
    ("es-PY", _(u"Spanish (Paraguay)")),
    ("es-SV", _(u"Spanish (El Salvador)")),
    ("es-UY", _(u"Spanish (Uruguay)")),
    ("es-VE", _(u"Spanish (Venezuela)")),
    ("et", _(u"Estonian")),
    ("et-EE", _(u"Estonian (Estonia)")),
    ("eu", _(u"Basque")),
    ("eu-ES", _(u"Basque (Spain)")),
    ("fa", _(u"Farsi")),
    ("fa-IR", _(u"Farsi (Iran)")),
    ("fi", _(u"Finnish")),
    ("fi-FI", _(u"Finnish (Finland)")),
    ("fo", _(u"Faroese")),
    ("fo-FO", _(u"Faroese (Faroe Islands)")),
    ("fr", _(u"French")),
    ("fr-BE", _(u"French (Belgium)")),
    ("fr-CA", _(u"French (Canada)")),
    ("fr-CH", _(u"French (Switzerland)")),
    ("fr-FR", _(u"French (France)")),
    ("fr-LU", _(u"French (Luxembourg)")),
    ("fr-MC", _(u"French (Principality of Monaco)")),
    ("gl", _(u"Galician")),
    ("gl-ES", _(u"Galician (Spain)")),
    ("gu", _(u"Gujarati")),
    ("gu-IN", _(u"Gujarati (India)")),
    ("he", _(u"Hebrew")),
    ("he-IL", _(u"Hebrew (Israel)")),
    ("hi", _(u"Hindi")),
    ("hi-IN", _(u"Hindi (India)")),
    ("hr", _(u"Croatian")),
    ("hr-BA", _(u"Croatian (Bosnia and Herzegovina)")),
    ("hr-HR", _(u"Croatian (Croatia)")),
    ("hu", _(u"Hungarian")),
    ("hu-HU", _(u"Hungarian (Hungary)")),
    ("hy", _(u"Armenian")),
    ("hy-AM", _(u"Armenian (Armenia)")),
    ("id", _(u"Indonesian")),
    ("id-ID", _(u"Indonesian (Indonesia)")),
    ("is", _(u"Icelandic")),
    ("is-IS", _(u"Icelandic (Iceland)")),
    ("it", _(u"Italian")),
    ("it-CH", _(u"Italian (Switzerland)")),
    ("it-IT", _(u"Italian (Italy)")),
    ("ja", _(u"Japanese")),
    ("ja-JP", _(u"Japanese (Japan)")),
    ("ka", _(u"Georgian")),
    ("ka-GE", _(u"Georgian (Georgia)")),
    ("kk", _(u"Kazakh")),
    ("kk-KZ", _(u"Kazakh (Kazakhstan)")),
    ("kn", _(u"Kannada")),
    ("kn-IN", _(u"Kannada (India)")),
    ("ko", _(u"Korean")),
    ("ko-KR", _(u"Korean (Korea)")),
    ("kok", _(u"Konkani")),
    ("kok-IN", _(u"Konkani (India)")),
    ("ky", _(u"Kyrgyz")),
    ("ky-KG", _(u"Kyrgyz (Kyrgyzstan)")),
    ("lt", _(u"Lithuanian")),
    ("lt-LT", _(u"Lithuanian (Lithuania)")),
    ("lv", _(u"Latvian")),
    ("lv-LV", _(u"Latvian (Latvia)")),
    ("mi", _(u"Maori")),
    ("mi-NZ", _(u"Maori (New Zealand)")),
    ("mk", _(u"FYRO Macedonian")),
    ("mk-MK", _(u"FYRO Macedonian (Former Yugoslav Republic of Macedonia)")),
    ("mn", _(u"Mongolian")),
    ("mn-MN", _(u"Mongolian (Mongolia)")),
    ("mr", _(u"Marathi")),
    ("mr-IN", _(u"Marathi (India)")),
    ("ms", _(u"Malay")),
    ("ms-BN", _(u"Malay (Brunei Darussalam)")),
    ("ms-MY", _(u"Malay (Malaysia)")),
    ("mt", _(u"Maltese")),
    ("mt-MT", _(u"Maltese (Malta)")),
    ("nb", _(u"Norwegian (Bokm?l)")),
    ("nb-NO", _(u"Norwegian (Bokm?l) (Norway)")),
    ("nl", _(u"Dutch")),
    ("nl-BE", _(u"Dutch (Belgium)")),
    ("nl-NL", _(u"Dutch (Netherlands)")),
    ("nn-NO", _(u"Norwegian (Nynorsk) (Norway)")),
    ("ns", _(u"Northern Sotho")),
    ("ns-ZA", _(u"Northern Sotho (South Africa)")),
    ("pa", _(u"Punjabi")),
    ("pa-IN", _(u"Punjabi (India)")),
    ("pl", _(u"Polish")),
    ("pl-PL", _(u"Polish (Poland)")),
    ("ps", _(u"Pashto")),
    ("ps-AR", _(u"Pashto (Afghanistan)")),
    ("pt", _(u"Portuguese")),
    ("pt-BR", _(u"Portuguese (Brazil)")),
    ("pt-PT", _(u"Portuguese (Portugal)")),
    ("qu", _(u"Quechua")),
    ("qu-BO", _(u"Quechua (Bolivia)")),
    ("qu-EC", _(u"Quechua (Ecuador)")),
    ("qu-PE", _(u"Quechua (Peru)")),
    ("ro", _(u"Romanian")),
    ("ro-RO", _(u"Romanian (Romania)")),
    ("ru", _(u"Russian")),
    ("ru-RU", _(u"Russian (Russia)")),
    ("sa", _(u"Sanskrit")),
    ("sa-IN", _(u"Sanskrit (India)")),
    ("se", _(u"Sami (Northern)")),
    ("se-FI", _(u"Sami (Northern) (Finland)")),
    ("se-FI", _(u"Sami (Skolt) (Finland)")),
    ("se-FI", _(u"Sami (Inari) (Finland)")),
    ("se-NO", _(u"Sami (Northern) (Norway)")),
    ("se-NO", _(u"Sami (Lule) (Norway)")),
    ("se-NO", _(u"Sami (Southern) (Norway)")),
    ("se-SE", _(u"Sami (Northern) (Sweden)")),
    ("se-SE", _(u"Sami (Lule) (Sweden)")),
    ("se-SE", _(u"Sami (Southern) (Sweden)")),
    ("sk", _(u"Slovak")),
    ("sk-SK", _(u"Slovak (Slovakia)")),
    ("sl", _(u"Slovenian")),
    ("sl-SI", _(u"Slovenian (Slovenia)")),
    ("sq", _(u"Albanian")),
    ("sq-AL", _(u"Albanian (Albania)")),
    ("sr-BA", _(u"Serbian (Latin) (Bosnia and Herzegovina)")),
    ("sr-BA", _(u"Serbian (Cyrillic) (Bosnia and Herzegovina)")),
    ("sr-SP", _(u"Serbian (Latin) (Serbia and Montenegro)")),
    ("sr-SP", _(u"Serbian (Cyrillic) (Serbia and Montenegro)")),
    ("sv", _(u"Swedish")),
    ("sv-FI", _(u"Swedish (Finland)")),
    ("sv-SE", _(u"Swedish (Sweden)")),
    ("sw", _(u"Swahili")),
    ("sw-KE", _(u"Swahili (Kenya)")),
    ("syr", _(u"Syriac")),
    ("syr-SY", _(u"Syriac (Syria)")),
    ("ta", _(u"Tamil")),
    ("ta-IN", _(u"Tamil (India)")),
    ("te", _(u"Telugu")),
    ("te-IN", _(u"Telugu (India)")),
    ("th", _(u"Thai")),
    ("th-TH", _(u"Thai (Thailand)")),
    ("tl", _(u"Tagalog")),
    ("tl-PH", _(u"Tagalog (Philippines)")),
    ("tn", _(u"Tswana")),
    ("tn-ZA", _(u"Tswana (South Africa)")),
    ("tr", _(u"Turkish")),
    ("tr-TR", _(u"Turkish (Turkey)")),
    ("tt", _(u"Tatar")),
    ("tt-RU", _(u"Tatar (Russia)")),
    ("ts", _(u"Tsonga")),
    ("uk", _(u"Ukrainian")),
    ("uk-UA", _(u"Ukrainian (Ukraine)")),
    ("ur", _(u"Urdu")),
    ("ur-PK", _(u"Urdu (Islamic Republic of Pakistan)")),
    ("uz", _(u"Uzbek (Latin)")),
    ("uz-UZ", _(u"Uzbek (Latin) (Uzbekistan)")),
    ("uz-UZ", _(u"Uzbek (Cyrillic) (Uzbekistan)")),
    ("vi", _(u"Vietnamese")),
    ("vi-VN", _(u"Vietnamese (Viet Nam)")),
    ("xh", _(u"Xhosa")),
    ("xh-ZA", _(u"Xhosa (South Africa)")),
    ("zh", _(u"Chinese")),
    ("zh-CN", _(u"Chinese (S)")),
    ("zh-HK", _(u"Chinese (Hong Kong)")),
    ("zh-MO", _(u"Chinese (Macau)")),
    ("zh-SG", _(u"Chinese (Singapore)")),
    ("zh-TW", _(u"Chinese (T)")),
    ("zu", _(u"Zulu")),
    ("zu-ZA", _(u"Zulu (South Africa)")),
)

